image: node

pages:
    stage: deploy
    cache:
        paths:
            - node_modules/
            - yarn.lock
    script:
        - npm install
        - npm run build
        - rm -Rf public
        - mv build public
        - cp public/index-gitlab.html public/index.html
        - rm public/index-gitlab.html
    artifacts:
        paths:
            - public
    only:
        - master
