version: '3.8'

name: edsystems

services:
    rust:
        container_name: edsystem-rust
        build: .
        volumes:
            - .:/app
            
        # tty: true
        # command: /bin/bash

        command: /usr/src/ejecutable


networks:
    default:
        name: proxylan

